replicaCount: 1

image:
  pullPolicy: IfNotPresent

elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch:7.17.12
  replicas: 1
  ports:
    - name: http
      port: 9200

logstash:
  image: docker.elastic.co/logstash/logstash:7.17.12
  replicas: 1
  ports:
    - name: beats
      port: 5044

kibana:
  image: docker.elastic.co/kibana/kibana:7.17.12
  replicas: 1
  ports:
    - name: ui
      port: 5601

persistence:
  enabled: true
  size: 10Gi
  accessMode: ReadWriteOnce
  storageClass: ""

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

