apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  labels:
    {{- include "elk.labels" . | nindent 4 }}
data:
  elasticsearch.yml: |
    cluster.name: "docker-cluster"
    network.host: 0.0.0.0
    discovery.type: single-node

