apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    {{- include "elk.labels" . | nindent 4 }}
spec:
  ports:
  - port: 5601
    targetPort: 5601
  selector:
    app: kibana
  type: NodePort

